///////////////tools/
		__init__.py
		validate/
				__init__.py
				validate.py
			view/
				__init__.py
				view.py
				clientes/
						__init__.py
						clientes.py
							productos/
									__init__.py
									productos.py
										servicios/
												__init__.py
												servicios.py
															mascotas/
																	__init__
																	mascotas.py
																		historiales_clinicos/
																							__init__
																							historiales_clinicos.py
																								facturas/
																										__init__
																										facturas.py